### ISSUE TITLE
Line endings should be LS

### ISSUE THREAD

**Issue by jorisroling** [AndersDJohnson/eyes-cli#1]
For the hashbang first line in cli.js to work, the file should be saved as unix textfile (lineending=LF ), you have a windows lineending (CRLF),  which gives a `env: node\r: No such file or directory` error on linux.

**Comment by AndersDJohnson** [comment]
@jorisroling Are you checking it out on Windows or in CRLF mode? I don't see `\r` characters in `cli.js` in my checkout. https://help.github.com/articles/dealing-with-line-endings/

**Comment by jorisroling** [comment]
I just installed it with npm on my mac.

 Download   Email (https://itunes.apple.com/app/apple-store/id922793622?pt=814382&mt=8&ct=download_email)

**Comment by AndersDJohnson** [comment]
@jorisroling Odd, I got the same thing from an npm install. Fixed since version 0.0.3 pushed to npm.

**Comment by jorisroling** [comment]
That is probably the issue, I just checked, I have version 0.0.2 here. Don't know why...

**Comment by jorisroling** [comment]
Doing `npm update eyes-cli -g` seems to solve it... thnx
